services:
  api:
    build:
      context: ./API
      dockerfile: sae-api.Dockerfile
    image: sae_api
    container_name: sae_api
    ports:
      - "3000:3000"
    restart: always

  webapp:
    build:
      context: ./webapp
      dockerfile: sae-webapp.Dockerfile
    image: sae_webapp
    container_name: sae_webapp
    ports:
      - "3001:3001"
    restart: always

  api_doc:
    build:
      context: ./API/doc
      dockerfile: sae-api-doc.Dockerfile
    image: sae_api_doc
    container_name: sae_api_doc
    ports:
      - "3002:80"
    restart: always

  webapp_doc:
    build:
      context: ./webapp/doc
      dockerfile: sae-webapp-doc.Dockerfile
    image: sae_webapp_doc
    container_name: sae_webapp_doc
    ports:
      - "3003:80"
    restart: always